name: Bug report
description: Report a bug
title: "[bug] "
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      placeholder: What happened?
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: ocv version
      placeholder: run ocv --version

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      placeholder: |
        1.
        2.
        3.
