name: Feature request
description: Suggest a new feature
labels: ["feature"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      placeholder: What do you want to see?
    validations:
      required: true
